version: '3'
volumes:
  data:

services:
  mongo:
    image: mongo:3.6
    restart: always
    volumes:
      - data:/data/db
    ports:
      - "1817:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=hudozka
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_HUDOZKA_PASSWORD}

  app:
    restart: always
    depends_on:
      - mongo
    build:
      context: ./
      dockerfile: Hudozka.Dockerfile
    links:
      - mongo
    ports:
      - "1880:3000"
    environment:
      - DB_URI=${HUDOZKA_DB_URI}

