---
database_uri: 'mongodb://localhost:27017/hudozka'

env: 'production'
origin: 'Yandex.Disk'
yandex_disk_access_token: '<YANDEX_DISK_TOKEN>'
interval: 0

skip_unchanged: True

image_processing_enabled: True

upload_enabled: True
upload_auth:
  login: '<LOGIN>'
  password: '<PASSWORD>'

provider:
  name: 'fs'
  root: '<FS_ROOT>'

update_enabled: True
delete_enabled: True
